# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # For Yarn, use 'npm'
    directory: "/" # Assuming package.json and yarn.lock are in the root
    schedule:
      interval: "weekly" # Dependabot will check for updates weekly
  - package-ecosystem: "solidity"
    directory: "/contracts" # Replace with the correct path
    schedule:
      interval: "weekly"
